apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: backend
          image: rukengokc/todo-backend:latest
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: todo-backend-config

